name: staging deploy
on: [push]
branch : [devlopment]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@development
      - name: deploy website to http://staging.bensresume.co.za/
        uses: appleboy/scp-action@development
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "dest/*"
          target: "/home/staging.ben/public_html"
          strip_components: 1